/* =================================================================
   KNOW YOUR PEARLS — client-provided guide content
   -----------------------------------------------------------------
   Source: "Mahidha - Know your pearls" document supplied by the
   client. Body entries use light markers that the page renderer
   understands: "### " = sub-heading, "#### " = minor heading,
   "- " = bullet item (consecutive items form one list); everything
   else renders as a paragraph. Images were extracted from the same
   document and live in /public/img/pearls.
   ================================================================= */

const P = "/img/pearls/";

export interface GalleryImage {
  src: string;
  alt: string;
}

export interface PearlSection {
  id: string;
  name: string;
  tagline: string;
  images: GalleryImage[];
  body: string[];
  facts: [string, string][];
  didYouKnow: string;
}

export const INTRO =
  "Every pearl tells a different story. They are shaped by the waters they grow in, the mollusks that nurture them, and the time nature allows them to develop. While all pearls share the same magical lustre, no two varieties are truly alike. Understanding where a pearl comes from helps you appreciate not just its beauty, but its rarity and craftsmanship.";

export const VARIETIES: PearlSection[] = [
  {
    id: "freshwater",
    name: "Freshwater Pearls",
    tagline: "The Pearl of Everyday Elegance",
    images: [
      { src: P + "freshwater-1.jpg", alt: "Freshwater pearl necklace styled with a white outfit" },
      { src: P + "freshwater-2.jpg", alt: "Naturally coloured freshwater pearls resting in a shell" },
      { src: P + "freshwater-3.jpg", alt: "Freshwater pearl necklace on soft ivory fabric" },
    ],
    body: [
      "Freshwater pearls have an effortless charm that has captivated jewellery lovers for centuries. Softly luminous, naturally unique, and wonderfully versatile, they are among the most cherished pearls in the world. Whether worn with a crisp white shirt at work or paired with an elegant evening dress, freshwater pearls have a timeless quality that never goes out of style.",
      "Unlike gemstones that are mined from the earth, pearls are created by living mollusks. They are the only gemstones born from nature through a biological process, making each pearl a remarkable work of art. Every freshwater pearl carries subtle differences in shape, colour, and lustre, ensuring that no two are ever exactly alike.",
      "At Mahidha, we celebrate these natural variations because they tell the story of the pearl's journey. They remind us that true beauty is found in individuality, not perfection.",
      "### What Are Freshwater Pearls?",
      "Freshwater pearls are cultured inside freshwater mussels that live in lakes, rivers, and ponds. Today, the majority of the world's freshwater pearls are cultivated in China, where generations of skilled farmers have refined pearl cultivation into a remarkable blend of science, patience, and craftsmanship.",
      "Unlike saltwater oysters, a single freshwater mussel can produce several pearls at once. This makes freshwater pearls more widely available while still requiring years of careful nurturing before they are ready to be harvested.",
      "The process is slow and entirely dependent on nature. Farmers can guide the cultivation, but they cannot rush it. Time is what gives each pearl its beautiful layers of nacre and its unmistakable glow.",
      "### How Are Freshwater Pearls Formed?",
      "The journey of a freshwater pearl begins with a tiny piece of mantle tissue that is carefully placed inside a healthy freshwater mussel by skilled technicians. In response, the mussel naturally begins coating the tissue with thousands of microscopic layers of nacre, the same iridescent material that gives pearls their beauty.",
      "Over the next two to five years, these delicate layers slowly build upon one another until a pearl is formed. The longer the pearl remains inside the mussel, the thicker its nacre becomes, resulting in greater durability and a richer lustre.",
      "This remarkable process cannot be hurried. Every pearl grows at its own pace, shaped by water quality, climate, and the natural conditions in which it develops.",
      "### A Palette Created by Nature",
      "Freshwater pearls are admired for their beautiful range of natural colours. While classic white remains the most popular choice, nature also produces elegant shades of cream, ivory, peach, pink, and soft lavender.",
      "Each colour has its own personality. White pearls offer timeless sophistication, peach pearls bring warmth and romance, while lavender pearls add a contemporary touch with their gentle, pastel glow.",
      "Some darker colours available in the market are achieved through specialised treatments, but the soft, natural shades remain among the most sought after for fine jewellery.",
      "### Shapes That Make Every Pearl Unique",
      "One of the most fascinating characteristics of freshwater pearls is their incredible variety of shapes. While perfectly round pearls are highly prized, many jewellery lovers are drawn to pearls that embrace their natural individuality.",
      "Freshwater pearls may be round, oval, button-shaped, drop-shaped, rice-shaped, coin-shaped, or beautifully baroque with organic, free-flowing forms. These distinctive shapes allow designers to create jewellery that feels artistic, contemporary, and truly one of a kind.",
      "Rather than viewing these variations as imperfections, they should be appreciated as nature's signature.",
      "### The Beauty of Freshwater Pearl Lustre",
      "Lustre is the quality that gives a pearl its glow. Freshwater pearls are known for their soft, silky radiance that appears to come from within rather than simply reflecting light from the surface.",
      "This gentle luminosity creates an elegant, understated look that complements every skin tone and every occasion. Their quiet beauty is one of the reasons freshwater pearls have become a favourite for everyday jewellery.",
      "### Why Choose Freshwater Pearls?",
      "Freshwater pearls offer an exceptional balance of beauty, durability, and versatility. Their thick nacre makes them resilient enough for regular wear, while their timeless appeal allows them to complement both modern and traditional styles.",
      "They transition effortlessly from daytime meetings to festive celebrations, making them one of the most wearable gemstones in any jewellery collection.",
      "For those beginning their pearl journey, freshwater pearls are often the perfect introduction to the enduring elegance of pearls.",
      "### Caring for Your Freshwater Pearls",
      "Pearls are organic gemstones and deserve gentle care to preserve their natural beauty.",
      "After wearing your jewellery, simply wipe the pearls with a soft, dry cloth to remove any traces of perfume, makeup, or natural oils. Store them separately from harder gemstones to avoid scratches, and avoid prolonged exposure to chemicals, excessive heat, or chlorinated water.",
      "With thoughtful care, freshwater pearls can retain their lustre for generations.",
      "### Mahidha's Perspective",
      "At Mahidha, freshwater pearls hold a special place in our collections. Their natural elegance, graceful glow, and subtle individuality reflect everything we believe fine jewellery should be.",
      "We carefully select pearls for their lustre, balance, and character, allowing their natural beauty to shine through thoughtful craftsmanship. Rather than chasing uniformity, we embrace the unique details that make every pearl one of a kind.",
      "Each Mahidha piece is designed to become part of your everyday story, celebrating moments both ordinary and extraordinary with jewellery that feels timeless, personal, and effortlessly elegant.",
    ],
    facts: [
      ["Type", "Cultured freshwater pearl"],
      ["Origin", "Lakes, rivers, and ponds, primarily in China"],
      ["Host", "Freshwater mussel"],
      ["Cultivation Time", "Approximately 2 to 5 years"],
      ["Natural Colours", "White, cream, ivory, peach, pink, lavender"],
      ["Common Shapes", "Round, oval, button, drop, rice, coin, baroque"],
      ["Lustre", "Soft, silky, satin-like glow"],
      ["Best Known For", "Everyday elegance, versatility, and natural beauty"],
    ],
    didYouKnow:
      "A single freshwater mussel can produce multiple pearls during one cultivation cycle, but each pearl develops its own unique shape, colour, and lustre. That is why no two freshwater pearls are ever truly identical, making every piece of pearl jewellery beautifully unique.",
  },
  {
    id: "south-sea",
    name: "South Sea Pearls",
    tagline: "The Queen of Pearls",
    images: [
      { src: P + "south-sea-1.jpg", alt: "Golden South Sea pearl necklace and earrings worn with a white dress" },
      { src: P + "south-sea-2.jpg", alt: "Golden and white South Sea pearls up close" },
      { src: P + "south-sea-3.jpg", alt: "South Sea pearl strand with a diamond clasp" },
    ],
    body: [
      "South Sea pearls are often regarded as the finest cultured pearls in the world. Celebrated for their exceptional size, luxurious lustre, and natural beauty, they are the pinnacle of pearl craftsmanship. Every South Sea pearl is the result of years of patience, pristine marine environments, and nature's quiet artistry.",
      "Unlike pearls with a bright, mirror-like shine, South Sea pearls are admired for their deep, satin-like glow that seems to radiate from within. Their elegance is understated yet unmistakable, making them a favourite among collectors, jewellery connoisseurs, and those who appreciate timeless luxury.",
      "At Mahidha, we see South Sea pearls as more than beautiful gemstones. They are symbols of rarity, craftsmanship, and enduring sophistication.",
      "### What Are South Sea Pearls?",
      "South Sea pearls are saltwater cultured pearls produced by the Pinctada maxima, the largest pearl oyster in the world. These oysters thrive in the warm, crystal-clear waters of the South Pacific and the Indian Ocean, where ideal conditions allow pearls to grow slowly and develop their remarkable beauty.",
      "Unlike freshwater mussels that can produce several pearls at once, a single South Sea oyster is typically cultivated for just one pearl at a time. This limited production, combined with the years required for cultivation, makes South Sea pearls among the rarest and most valuable cultured pearls available today.",
      "### Where Do South Sea Pearls Come From?",
      "The finest South Sea pearls are cultivated in some of the world's most pristine coastal waters, including:",
      "- Australia",
      "- Indonesia",
      "- The Philippines",
      "- Myanmar",
      "Australia is particularly renowned for its luminous white and silver South Sea pearls, while Indonesia and the Philippines are famous for producing beautiful golden varieties.",
      "The purity of these waters plays a vital role in creating pearls with exceptional lustre, thick nacre, and outstanding quality.",
      "### How Are South Sea Pearls Formed?",
      "The cultivation of a South Sea pearl is a highly skilled process that combines expertise with patience.",
      "A carefully selected oyster receives a small round nucleus along with a tiny piece of mantle tissue. Once the oyster is returned to the sea, it begins coating the nucleus with thousands of microscopic layers of nacre.",
      "Over the next two to four years, the pearl slowly develops inside the oyster. During this time, pearl farmers regularly monitor the oysters, ensuring they remain healthy and protected from changes in water quality and marine conditions.",
      "Even with years of care, not every oyster produces a gem-quality pearl. Many reject the nucleus, while others produce pearls that do not meet the high standards expected for fine jewellery. This natural unpredictability is one of the reasons South Sea pearls are so highly prized.",
      "### The Beauty of Size and Lustre",
      "South Sea pearls are the largest commercially cultivated pearls in the world, typically ranging from 8 mm to 20 mm, with exceptional pearls growing even larger.",
      "Their size is complemented by an unusually thick layer of nacre, which gives them a rich, silky glow. Instead of reflecting light sharply, South Sea pearls display a soft, velvety lustre that creates a sense of depth and warmth.",
      "This distinctive radiance is one of the defining characteristics that sets South Sea pearls apart from other pearl varieties.",
      "### Naturally Beautiful Colours",
      "One of the most remarkable qualities of South Sea pearls is their naturally occurring colour palette. Common natural shades include:",
      "- White",
      "- Silver White",
      "- Cream",
      "- Ivory",
      "- Champagne",
      "- Soft Gold",
      "- Deep Golden",
      "Golden South Sea pearls are especially admired for their rich, warm tones, which develop naturally inside the gold-lipped oyster rather than through artificial colouring.",
      "Subtle overtones of pink, silver, or green may also appear, adding depth and individuality to each pearl.",
      "### Shapes That Celebrate Nature",
      "Although perfectly round South Sea pearls are the rarest and most valuable, nature creates them in many elegant forms. These include round, near round, oval, drop, button, circle, semi-baroque, and baroque.",
      "Each shape has its own appeal, and many contemporary jewellery designs embrace the organic beauty of baroque South Sea pearls for their sculptural character and individuality.",
      "### Why Are South Sea Pearls So Valuable?",
      "The rarity of South Sea pearls comes down to time, nature, and patience.",
      "Each pearl takes years to develop inside a single oyster, and only a small percentage achieve the size, lustre, and surface quality required for high-end jewellery. Their thick nacre, limited production, and meticulous cultivation contribute to their exceptional value.",
      "Unlike many luxury items that are manufactured, every South Sea pearl is shaped by nature. No technology can replicate the beauty that develops over years beneath the sea.",
      "### Caring for South Sea Pearls",
      "South Sea pearls are treasured heirlooms and deserve gentle care.",
      "After wearing your jewellery, wipe the pearls with a soft cloth to remove any traces of cosmetics or natural oils. Store them separately from harder gemstones to prevent scratches, and avoid exposing them to harsh chemicals, perfumes, or prolonged sunlight.",
      "With proper care, South Sea pearls will retain their remarkable beauty for generations.",
      "### Mahidha's Perspective",
      "At Mahidha, South Sea pearls represent the highest expression of elegance. Their luminous glow, graceful proportions, and natural rarity inspire designs that are timeless rather than trend-driven.",
      "We carefully select pearls for their lustre, harmony, and character, allowing each one to remain the focal point of the jewellery. Every South Sea pearl in our collection is chosen with the belief that true luxury lies in authenticity, craftsmanship, and the quiet beauty that only nature can create.",
      "Whether worn for a milestone celebration or passed down as a cherished heirloom, South Sea pearls are designed to be treasured for a lifetime.",
    ],
    facts: [
      ["Type", "Cultured saltwater pearl"],
      ["Origin", "Australia, Indonesia, The Philippines, Myanmar"],
      ["Host", "Pinctada maxima oyster"],
      ["Cultivation Time", "Approximately 2 to 4 years"],
      ["Typical Size", "8 mm to 20 mm"],
      ["Natural Colours", "White, silver, cream, champagne, golden"],
      ["Common Shapes", "Round, oval, drop, button, circle, baroque"],
      ["Lustre", "Rich, silky, satin-like glow"],
      ["Best Known For", "Exceptional size, rarity, and luxurious appearance"],
    ],
    didYouKnow:
      "A South Sea pearl oyster can grow up to 30 centimetres (12 inches) in diameter, making it the largest pearl-producing oyster in the world. Its size allows it to create pearls with exceptionally thick nacre, giving South Sea pearls their signature soft glow and remarkable durability.",
  },
  {
    id: "akoya",
    name: "Akoya Pearls",
    tagline: "The Classic Pearl of Timeless Elegance",
    images: [
      { src: P + "akoya-1.jpg", alt: "Akoya pearl pendant styled with modern workwear" },
      { src: P + "akoya-2.jpg", alt: "Perfectly round Akoya pearl strand with mirror-like lustre" },
      { src: P + "akoya-3.jpg", alt: "A single luminous Akoya pearl on lace" },
    ],
    body: [
      "Akoya pearls are the pearls that most people imagine when they think of classic pearl jewellery. Perfectly round, luminous, and elegant, they have become the global symbol of sophistication for more than a century. Their crisp white colour and brilliant mirror-like lustre have made them a favourite for bridal jewellery, heirloom pieces, and timeless everyday elegance.",
      "While every pearl has its own beauty, Akoya pearls are celebrated for their remarkable symmetry and radiant shine. Their refined appearance has earned them a place in some of the world's most iconic jewellery collections and continues to make them one of the most sought-after pearl varieties today.",
      "At Mahidha, we admire Akoya pearls for their quiet confidence. They never compete for attention, yet they always leave a lasting impression.",
      "### What Are Akoya Pearls?",
      "Akoya pearls are cultured saltwater pearls produced by the Pinctada fucata martensii oyster, a smaller oyster native to the coastal waters of Japan and parts of China and Vietnam.",
      "Unlike freshwater pearls, which often grow in a variety of shapes, Akoya pearls are renowned for their near-perfect roundness. This natural symmetry, combined with their exceptional lustre, makes them one of the most recognisable and desirable pearls in the world.",
      "Although the oysters are relatively small, they produce pearls of extraordinary beauty that have defined classic pearl jewellery for generations.",
      "### A Legacy That Changed the Pearl Industry",
      "The story of Akoya pearls is closely linked to Kokichi Mikimoto, whose pioneering work transformed the jewellery world in the late 19th century.",
      "His success in cultivating pearls made these once-rare gems more accessible while maintaining their elegance and quality. Today, Japan remains synonymous with exceptional Akoya pearls and continues to uphold some of the highest standards in pearl cultivation.",
      "This rich heritage has made Akoya pearls a symbol of craftsmanship, innovation, and timeless luxury.",
      "### Where Do Akoya Pearls Come From?",
      "Akoya pearls are primarily cultivated in the calm coastal waters of Japan, China, and Vietnam.",
      "Japan is widely recognised for producing some of the finest Akoya pearls in the world. The country's cool, nutrient-rich waters help create pearls with exceptional lustre and beautifully balanced colours.",
      "The careful attention given to every stage of cultivation reflects generations of expertise passed down through skilled pearl farmers.",
      "### How Are Akoya Pearls Formed?",
      "The cultivation process begins when a skilled technician carefully places a small round nucleus and a tiny piece of mantle tissue inside the oyster.",
      "Over the next one to two years, the oyster coats the nucleus with layer upon layer of nacre, gradually creating a pearl.",
      "Throughout this period, pearl farmers regularly inspect the oysters to ensure they remain healthy and protected from changes in water temperature and marine conditions.",
      "Once harvested, every pearl is carefully evaluated for its shape, lustre, surface quality, and colour before being selected for fine jewellery.",
      "### The Signature Mirror-Like Lustre",
      "If there is one characteristic that defines an Akoya pearl, it is its extraordinary lustre.",
      "Akoya pearls reflect light with remarkable clarity, creating a bright, crisp shine often described as mirror-like. Their polished appearance gives jewellery a refined elegance that is instantly recognisable.",
      "This exceptional brilliance is one of the reasons Akoya pearls remain a favourite choice for classic necklaces, earrings, and bracelets.",
      "### Natural Colours",
      "Akoya pearls are best known for their elegant white tones, but nature offers a beautiful range of subtle shades. Natural colours include white, cream, silver white, and ivory.",
      "Many Akoya pearls also display delicate overtones of rose, silver, or cream. These gentle overtones add depth and warmth, giving each pearl its own unique character while maintaining a refined appearance.",
      "### Size and Shape",
      "Akoya pearls are generally smaller than South Sea pearls, with sizes typically ranging from 2 mm to 10 mm, although larger pearls are considerably rarer.",
      "They are especially prized for their round shape, making them ideal for jewellery designs that require symmetry and consistency. Common shapes include round, near round, oval, button, and — less commonly — baroque.",
      "Perfectly matched strands of Akoya pearls are highly valued because achieving such consistency requires careful selection.",
      "### Why Choose Akoya Pearls?",
      "Akoya pearls are the perfect choice for those who appreciate timeless elegance.",
      "Their brilliant lustre, refined size, and classic appearance make them suitable for almost every occasion, from weddings and celebrations to everyday sophistication.",
      "Whether worn as a single strand, delicate earrings, or a simple bracelet, Akoya pearls have a graceful presence that never goes out of fashion. Their enduring appeal has made them one of the most treasured pearl varieties across generations.",
      "### Caring for Akoya Pearls",
      "Like all pearls, Akoya pearls benefit from gentle care.",
      "After wearing them, wipe each pearl with a soft cloth to remove any traces of cosmetics, perfume, or natural oils. Store them separately from harder gemstones to prevent scratches, and avoid exposing them to harsh chemicals or prolonged heat.",
      "With proper care, Akoya pearls will maintain their beautiful lustre for many years.",
      "### Mahidha's Perspective",
      "At Mahidha, Akoya pearls embody timeless refinement. Their luminous brilliance and graceful proportions make them an enduring choice for jewellery that celebrates life's most meaningful moments.",
      "We value their remarkable lustre and elegant simplicity, designing pieces that allow each pearl to shine naturally without unnecessary embellishment.",
      "An Akoya pearl is more than a classic accessory. It is a reminder that true elegance is often found in the simplest forms.",
    ],
    facts: [
      ["Type", "Cultured saltwater pearl"],
      ["Origin", "Japan, China, Vietnam"],
      ["Host", "Pinctada fucata martensii oyster"],
      ["Cultivation Time", "Approximately 1 to 2 years"],
      ["Typical Size", "2 mm to 10 mm"],
      ["Natural Colours", "White, cream, ivory, silver white"],
      ["Common Overtones", "Rose, silver, cream"],
      ["Common Shapes", "Round, near round, oval, button"],
      ["Lustre", "Bright, crisp, mirror-like"],
      ["Best Known For", "Classic beauty, exceptional lustre, perfect roundness"],
    ],
    didYouKnow:
      "Although Akoya pearls are generally smaller than South Sea pearls, they are often considered the benchmark for lustre. Their bright, mirror-like shine is so distinctive that jewellers around the world use Akoya pearls as the standard when evaluating the brilliance of other pearl varieties.",
  },
  {
    id: "tahitian",
    name: "Tahitian Pearls",
    tagline: "Nature's Dark Masterpiece",
    images: [
      { src: P + "tahitian-1.jpg", alt: "Tahitian pearl necklace styled with an all-black outfit" },
      { src: P + "tahitian-2.jpg", alt: "Tahitian pearls with peacock green and purple overtones" },
      { src: P + "tahitian-3.jpg", alt: "Dark Tahitian pearls up close" },
    ],
    body: [
      "Dark, mysterious, and undeniably elegant, Tahitian pearls are unlike any other pearls in the world. Often called black pearls, they are celebrated for their naturally deep colours and captivating overtones that shift beautifully in different light.",
      "Despite their name, Tahitian pearls are rarely pure black. Instead, they display a stunning spectrum of shades, from charcoal grey and silver to peacock green, aubergine, blue, and bronze. Their rich colours and exceptional lustre have made them one of the most distinctive and sought-after pearls in fine jewellery.",
      "At Mahidha, we admire Tahitian pearls for their individuality. Bold yet sophisticated, they offer a contemporary interpretation of timeless pearl jewellery.",
      "### What Are Tahitian Pearls?",
      "Tahitian pearls are cultured saltwater pearls produced by the Pinctada margaritifera, commonly known as the Black-Lipped Pearl Oyster. This remarkable oyster naturally creates pearls with darker body colours, giving Tahitian pearls their unmistakable appearance.",
      "Unlike pearls that are dyed to achieve darker shades, genuine Tahitian pearls develop their colour naturally inside the oyster. This natural beauty is one of the reasons they are so highly valued by collectors and jewellery enthusiasts around the world.",
      "Every Tahitian pearl is unique, with subtle variations in colour, overtone, and surface that make each one truly one of a kind.",
      "### Where Do Tahitian Pearls Come From?",
      "Although they are known as Tahitian pearls, most are cultivated throughout the pristine lagoons of French Polynesia, a collection of islands in the South Pacific Ocean. Important pearl farming regions include:",
      "- Tahiti",
      "- Bora Bora",
      "- Rangiroa",
      "- Tikehau",
      "- Fakarava",
      "The warm, crystal-clear waters of these islands provide the ideal environment for cultivating pearls with exceptional lustre and rich natural colours.",
      "French Polynesia is recognised worldwide for producing some of the highest quality Tahitian pearls available today.",
      "### How Are Tahitian Pearls Formed?",
      "The cultivation process begins when a skilled technician carefully inserts a round nucleus and a small piece of mantle tissue into the Black-Lipped Pearl Oyster.",
      "The oyster then begins coating the nucleus with thousands of delicate layers of nacre. Over the next 18 months to 3 years, these layers gradually form a beautiful pearl.",
      "During cultivation, pearl farmers regularly care for the oysters by cleaning them and monitoring water quality to ensure healthy growth.",
      "Even after years of careful attention, only a small percentage of harvested pearls display the exceptional colour, lustre, and surface quality required for fine jewellery.",
      "### A Colour Palette Unlike Any Other",
      "The greatest distinction of Tahitian pearls is their extraordinary range of natural colours. Rather than being simply black, Tahitian pearls may appear in shades of:",
      "- Charcoal Grey",
      "- Silver Grey",
      "- Peacock Green",
      "- Emerald Green",
      "- Aubergine",
      "- Blue",
      "- Bronze",
      "- Pistachio",
      "- Chocolate",
      "Many pearls also display beautiful overtones that change depending on how the light falls across their surface.",
      "Among all colours, the famous peacock overtone, which combines shades of green, blue, and purple, is considered one of the rarest and most desirable.",
      "### Lustre That Creates Depth",
      "Tahitian pearls are admired for their deep, reflective lustre.",
      "Instead of a soft satin glow, they often display a rich brilliance that enhances their darker body colours and colourful overtones. This gives each pearl remarkable depth and visual complexity.",
      "Their changing colours make Tahitian pearls especially captivating, appearing slightly different in natural daylight, indoor lighting, and evening settings.",
      "### Size and Shape",
      "Tahitian pearls are generally larger than Akoya pearls and typically range from 8 mm to 16 mm, with exceptional pearls growing even larger. Common shapes include round, near round, oval, drop, button, circle, and baroque.",
      "While perfectly round pearls remain highly prized, many jewellery designers embrace the unique beauty of baroque Tahitian pearls for their artistic and contemporary appeal.",
      "### Why Choose Tahitian Pearls?",
      "Tahitian pearls are perfect for those looking for something distinctive and unconventional.",
      "Their naturally dark colours make them remarkably versatile, pairing beautifully with both sterling silver and gold. Whether worn with monochrome outfits, evening wear, or modern tailoring, Tahitian pearls add sophistication without being overly traditional.",
      "Their individuality makes every piece of jewellery feel personal, ensuring no two designs are ever exactly alike.",
      "### Caring for Tahitian Pearls",
      "Like all fine pearls, Tahitian pearls should be handled with care.",
      "After wearing them, gently wipe the pearls with a soft cloth to remove any residue from skincare products or natural oils. Store them separately from harder jewellery to prevent scratches, and avoid exposing them to harsh chemicals, perfumes, or excessive heat.",
      "With proper care, their natural beauty will continue to shine for many years.",
      "### Mahidha's Perspective",
      "At Mahidha, Tahitian pearls represent confidence, individuality, and modern elegance. Their dramatic colours and remarkable lustre inspire jewellery that feels bold without being overwhelming.",
      "We carefully select Tahitian pearls for their depth of colour, luminous overtones, and natural character, creating designs that celebrate the beauty of imperfection and the artistry of nature.",
      "Whether chosen as a statement piece or worn every day, Tahitian pearls remind us that true elegance often lies in embracing what makes us unique.",
    ],
    facts: [
      ["Type", "Cultured saltwater pearl"],
      ["Origin", "French Polynesia"],
      ["Host", "Pinctada margaritifera (Black-Lipped Pearl Oyster)"],
      ["Cultivation Time", "Approximately 18 months to 3 years"],
      ["Typical Size", "8 mm to 16 mm"],
      ["Natural Colours", "Grey, silver, peacock green, blue, aubergine, bronze, pistachio"],
      ["Common Shapes", "Round, oval, drop, button, circle, baroque"],
      ["Lustre", "Rich, reflective, with colourful overtones"],
      ["Best Known For", "Naturally dark colours and unique iridescence"],
    ],
    didYouKnow:
      "Despite being called black pearls, very few Tahitian pearls are truly black. Their famous beauty comes from the natural overtones that shimmer across their surface, creating shades of green, blue, purple, silver, and bronze that change with the light. This extraordinary play of colour makes every Tahitian pearl completely unique.",
  },
  {
    id: "baroque",
    name: "Baroque Pearls",
    tagline: "Beauty in Its Most Natural Form",
    images: [
      { src: P + "baroque-1.jpg", alt: "Editorial portrait with layered baroque pearl jewellery" },
      { src: P + "baroque-2.jpg", alt: "Baroque pearl necklace with organic, free-flowing forms" },
      { src: P + "baroque-3.jpg", alt: "A pair of sculptural baroque pearl earrings" },
    ],
    body: [
      "Not every pearl is perfectly round, and that is exactly what makes baroque pearls so extraordinary.",
      "Baroque pearls are celebrated for their organic shapes, sculptural beauty, and unmistakable individuality. Each one is formed naturally, without following a predictable pattern, resulting in pearls that are wonderfully unique. Some resemble flowing teardrops, while others display soft curves, ripples, or abstract forms that make every piece feel like wearable art.",
      "In a world where perfection is often pursued, baroque pearls remind us that beauty can also be found in originality. Their distinctive character has made them a favourite among contemporary designers and collectors who appreciate jewellery with personality.",
      "At Mahidha, we embrace baroque pearls for their authenticity. No two are ever alike, and that is precisely what makes them so special.",
      "### What Are Baroque Pearls?",
      "Baroque pearls are pearls with irregular, asymmetrical shapes. Rather than growing into a perfect sphere, they develop naturally into unique forms that are impossible to replicate.",
      "The term baroque comes from the Portuguese word barroco, meaning “irregular pearl.” Over time, it became associated with artistic beauty that celebrates movement, creativity, and individuality.",
      "Baroque pearls can be found in both freshwater and saltwater varieties, including South Sea, Tahitian, and Akoya pearls. While their shapes may differ, they all share the same natural lustre and elegance that make pearls so timeless.",
      "### How Are Baroque Pearls Formed?",
      "Like all cultured pearls, baroque pearls begin their journey inside a mollusk.",
      "As layers of nacre are deposited, natural variations in the oyster or mussel, water conditions, and the pearl's growth can cause it to develop an irregular shape rather than a perfectly round one.",
      "This is not considered a flaw. Instead, it is a natural expression of the pearl's unique journey. Every curve, ridge, and contour tells a story that no other pearl can ever repeat.",
      "### Where Do Baroque Pearls Come From?",
      "Baroque pearls are cultivated in many of the world's leading pearl-producing regions, including China, Australia, Indonesia, French Polynesia, and Japan. They may come from freshwater mussels or saltwater oysters, depending on the variety.",
      "Whether grown in peaceful freshwater lakes or the clear waters of the South Pacific, every baroque pearl reflects the environment in which it was created.",
      "### A Celebration of Shape",
      "The beauty of baroque pearls lies in their endless diversity. Some of the most common forms include:",
      "- Teardrop",
      "- Oval",
      "- Coin",
      "- Flame",
      "- Elongated",
      "- Freeform",
      "- Sculptural",
      "- Organic",
      "Some pearls are softly curved and elegant, while others are dramatic and bold. Their irregular forms allow designers to create jewellery that feels artistic, modern, and impossible to duplicate.",
      "No two baroque pearls are ever identical.",
      "### Natural Colours",
      "Baroque pearls are available in an impressive range of natural colours, depending on the type of pearl. These include white, cream, ivory, silver, golden, pink, lavender, grey, peacock, and black.",
      "The colour palette makes baroque pearls incredibly versatile, allowing them to suit both minimalist and statement jewellery designs.",
      "### Lustre and Character",
      "Although baroque pearls are known for their unusual shapes, they can also display exceptional lustre.",
      "Their curved surfaces interact with light in fascinating ways, creating reflections that shift as the pearl moves. Some exhibit a soft satin glow, while others display brilliant, mirror-like lustre depending on the pearl variety.",
      "This ever-changing play of light gives baroque pearls a sense of movement and life that perfectly round pearls often cannot replicate.",
      "### Why Choose Baroque Pearls?",
      "Baroque pearls appeal to those who value individuality over uniformity.",
      "Their distinctive shapes make every necklace, bracelet, pendant, or pair of earrings feel completely unique. Rather than striving for perfect symmetry, they celebrate the beauty of nature exactly as it is.",
      "Their sculptural appearance also makes them incredibly versatile. They pair effortlessly with contemporary fashion while remaining elegant enough for formal occasions.",
      "For anyone looking to own jewellery that no one else will have, baroque pearls are a beautiful choice.",
      "### Caring for Baroque Pearls",
      "Baroque pearls require the same gentle care as all fine pearls.",
      "After wearing them, wipe them with a soft cloth to remove cosmetics, perfume, or natural oils. Store them separately from harder gemstones and avoid exposing them to harsh chemicals or excessive heat.",
      "With proper care, their natural beauty will continue to be enjoyed for generations.",
      "### Mahidha's Perspective",
      "At Mahidha, we believe perfection is not always symmetrical.",
      "Baroque pearls capture the beauty of nature in its most authentic form. Their flowing shapes, distinctive silhouettes, and organic elegance inspire jewellery that feels personal, expressive, and timeless.",
      "Rather than hiding their individuality, our designs celebrate it. Every baroque pearl is chosen for its character, balance, and natural beauty, ensuring that each Mahidha creation is as unique as the person who wears it.",
    ],
    facts: [
      ["Type", "Freshwater or saltwater cultured pearl"],
      ["Origin", "China, Australia, Indonesia, French Polynesia, Japan"],
      ["Host", "Freshwater mussels or saltwater oysters"],
      ["Cultivation Time", "Approximately 1 to 4 years, depending on the variety"],
      ["Natural Colours", "White, cream, golden, pink, lavender, silver, grey, peacock, black"],
      ["Common Shapes", "Freeform, teardrop, oval, coin, elongated, sculptural"],
      ["Lustre", "Soft satin to brilliant mirror-like, depending on the pearl type"],
      ["Best Known For", "Organic shapes, individuality, and artistic appeal"],
    ],
    didYouKnow:
      "For centuries, baroque pearls were prized by European royalty and master jewellers because of their unusual shapes. Many historic jewelled masterpieces featured baroque pearls that resembled flowers, birds, or mythical creatures, proving that nature's most unexpected creations often become its most extraordinary works of art.",
  },
  {
    id: "keshi",
    name: "Keshi Pearls",
    tagline: "Pure Nacre, Pure Beauty",
    images: [
      { src: P + "keshi-1.jpg", alt: "Keshi pearl necklace styled with an ivory dress" },
      { src: P + "keshi-2.jpg", alt: "Petal-shaped keshi pearl choker" },
      { src: P + "keshi-3.jpg", alt: "A freeform keshi pearl showing its rich lustre" },
    ],
    body: [
      "Some pearls are admired for their perfect symmetry. Others are treasured for something even rarer. Keshi pearls are loved for their exceptional lustre, organic beauty, and unique story of formation. Unlike most cultured pearls, Keshi pearls are composed almost entirely of nacre, giving them an extraordinary glow that is difficult to match.",
      "Lightweight, elegant, and completely one of a kind, Keshi pearls have become a favourite among jewellery designers who appreciate nature's artistry in its purest form.",
      "At Mahidha, we see Keshi pearls as a celebration of authenticity. Their free-flowing shapes and radiant lustre remind us that the most beautiful creations often come as nature's unexpected gifts.",
      "### What Are Keshi Pearls?",
      "Keshi pearls are unique pearls that form as a by-product during the pearl cultivation process. Unlike traditional cultured pearls, they develop without a bead nucleus, which means they are made almost entirely of solid nacre.",
      "The word “Keshi” comes from the Japanese word for “poppy seed,” a reference to the small size of the first Keshi pearls discovered in Japan. Today, Keshi pearls are available in a variety of sizes, from delicate accent pearls to larger statement pieces.",
      "Because they grow naturally without a nucleus, every Keshi pearl has its own distinctive shape, making each one truly unique.",
      "### How Are Keshi Pearls Formed?",
      "During the cultivation of a cultured pearl, an oyster or mussel may occasionally reject the implanted bead nucleus while retaining a small piece of mantle tissue.",
      "Rather than stopping the process, the mollusk continues producing nacre around this tissue, gradually creating a pearl made entirely of nacre.",
      "Since there is no bead at the centre, Keshi pearls are admired for their rich lustre and lightweight feel. Their formation is largely unpredictable, making them much rarer than standard cultured pearls.",
      "### Where Do Keshi Pearls Come From?",
      "Keshi pearls are produced in many of the world's leading pearl farming regions. They may originate from Japan, Australia, Indonesia, French Polynesia, and China.",
      "Keshi pearls can develop in both freshwater mussels and saltwater oysters, resulting in beautiful variations in size, colour, and appearance depending on their origin.",
      "### A Shape Like No Other",
      "Keshi pearls are instantly recognisable because of their naturally freeform shapes. Rather than growing into perfect spheres, they develop graceful, organic forms that resemble flower petals, ribbons, leaves, or tiny sculptures created by nature.",
      "Common shapes include:",
      "- Freeform",
      "- Petal",
      "- Feather",
      "- Nugget",
      "- Elongated",
      "- Organic",
      "Their irregular appearance allows jewellery designers to create contemporary pieces with movement, texture, and individuality. No two Keshi pearls will ever be exactly the same.",
      "### Exceptional Lustre",
      "If there is one feature that defines Keshi pearls, it is their extraordinary lustre.",
      "Because they are composed almost entirely of nacre, light travels beautifully through their layers, creating a radiant glow that appears rich, soft, and luminous.",
      "Many pearl lovers consider Keshi pearls to have some of the finest lustre of any cultured pearl, making them highly desirable despite their irregular shapes.",
      "### Natural Colours",
      "Keshi pearls are available in a wide range of natural colours, depending on the oyster or mussel that produced them. These include white, cream, silver, golden, pink, grey, peacock, and black.",
      "Saltwater Keshi pearls, particularly those from South Sea and Tahitian oysters, often display beautiful overtones and rich natural colours that enhance their unique character.",
      "### Why Choose Keshi Pearls?",
      "Keshi pearls are perfect for those who appreciate jewellery with individuality and artistic appeal.",
      "Their lightweight nature makes them comfortable to wear, while their organic shapes bring effortless elegance to both contemporary and classic designs.",
      "Whether featured in necklaces, earrings, bracelets, or pendants, Keshi pearls create jewellery that feels distinctive and naturally sophisticated. Every Keshi pearl tells its own story, making each piece truly one of a kind.",
      "### Caring for Keshi Pearls",
      "Although Keshi pearls are composed of thick nacre, they should still be cared for gently.",
      "After wearing your jewellery, wipe the pearls with a soft cloth and store them separately from harder gemstones. Avoid contact with perfumes, hairsprays, harsh chemicals, and prolonged exposure to direct sunlight.",
      "With proper care, Keshi pearls will continue to display their remarkable lustre for many years.",
      "### Mahidha's Perspective",
      "At Mahidha, Keshi pearls represent the beauty of the unexpected. Their natural forms, radiant glow, and remarkable individuality inspire jewellery that feels expressive, elegant, and effortlessly modern.",
      "Rather than seeking perfect uniformity, we celebrate the subtle variations that make every Keshi pearl unique. Each pearl is carefully selected for its lustre, character, and balance, allowing nature's artistry to remain at the heart of every design.",
      "To us, Keshi pearls are a reminder that true beauty is often found in what cannot be replicated.",
    ],
    facts: [
      ["Type", "Freshwater or saltwater cultured pearl without a bead nucleus"],
      ["Origin", "Japan, Australia, Indonesia, French Polynesia, China"],
      ["Host", "Freshwater mussels or saltwater oysters"],
      ["Composition", "Almost entirely nacre"],
      ["Natural Colours", "White, cream, silver, golden, pink, grey, peacock, black"],
      ["Common Shapes", "Freeform, petal, feather, nugget, elongated"],
      ["Lustre", "Exceptionally bright and luminous"],
      ["Best Known For", "Pure nacre, organic shapes, and remarkable lustre"],
    ],
    didYouKnow:
      "Keshi pearls are often described as nature's happy surprise. They form unexpectedly during the pearl cultivation process and are made almost entirely of nacre, which is why many collectors consider them among the most luminous pearls in the world.",
  },
  {
    id: "basra-toned",
    name: "Basra-Toned Pearls",
    tagline: "Inspired by a Legendary Legacy",
    images: [],
    body: [
      "For centuries, Basra pearls have been regarded as some of the finest and rarest pearls ever discovered. Admired by royalty, collectors, and connoisseurs across the world, these natural pearls became symbols of elegance, heritage, and exceptional craftsmanship. Their soft, creamy glow and understated beauty earned them a legendary place in the history of fine jewellery.",
      "Today, genuine Basra pearls are extraordinarily rare and are found primarily in museums, antique collections, and prestigious auctions.",
      "At Mahidha, we honour this remarkable legacy through our Basra-toned pearls. Inspired by the timeless beauty of historic Basra pearls, these cultured pearls are carefully selected for their warm ivory tones, soft lustre, and classic elegance, offering a contemporary interpretation of one of history's most celebrated pearls.",
      "### The Story Behind Basra Pearls",
      "The name Basra comes from the historic port city of Basra in present-day Iraq, one of the world's most important centres for the pearl trade between the 16th and early 20th centuries.",
      "Interestingly, these pearls were not harvested in the city itself. They were naturally formed in wild pearl oysters found in the waters of the Arabian Gulf, particularly around present-day Bahrain, Kuwait, Qatar, and the surrounding coastline. Merchants brought these precious pearls to the bustling markets of Basra before exporting them across India, Persia, Europe, and the Middle East.",
      "Over time, the name “Basra Pearls” became synonymous with exceptional quality and timeless luxury.",
      "### What Made Basra Pearls So Special?",
      "Unlike cultured pearls, historic Basra pearls formed entirely by nature without any human intervention.",
      "Divers spent months at sea searching for wild pearl oysters, often opening thousands before discovering a single gem-quality pearl. Their rarity, combined with their delicate beauty, made Basra pearls highly prized by royal families and wealthy collectors.",
      "They became especially popular in India during the Mughal era and later among the Nizams of Hyderabad, whose magnificent jewellery collections featured some of the world's finest pearls.",
      "Even today, genuine Basra pearls remain among the rarest natural gems in existence.",
      "### What Does “Basra-Toned” Mean?",
      "Basra-toned pearls are not natural Basra pearls. Instead, they are high-quality cultured pearls chosen for their colour and appearance, inspired by the gentle elegance of historic Basra pearls.",
      "The term Basra-toned refers to a beautiful colour palette rather than a geographical origin. These pearls are admired for their:",
      "- Warm ivory and cream tones",
      "- Soft, elegant lustre",
      "- Classic and understated appearance",
      "- Timeless versatility",
      "Their refined colouring captures the graceful character that made historic Basra pearls so admired for centuries.",
      "### The Beauty of Basra-Toned Pearls",
      "One of the defining characteristics of Basra-toned pearls is their subtle, natural warmth. Rather than displaying a bright white finish, they feature delicate shades of soft ivory, cream, warm white, champagne, and pale beige.",
      "These gentle tones flatter every skin tone and pair beautifully with both sterling silver and gold, making them an elegant choice for everyday wear as well as special occasions.",
      "Their understated beauty allows the craftsmanship of each jewellery piece to shine without feeling overly ornate.",
      "### Lustre That Feels Effortless",
      "Basra-toned pearls are appreciated for their soft, satin-like lustre.",
      "Instead of producing sharp reflections, they display a gentle glow that creates an elegant and sophisticated look. This subtle radiance makes them especially popular among those who appreciate jewellery that feels refined, timeless, and easy to wear.",
      "Their quiet beauty complements both traditional and contemporary designs.",
      "### Why Choose Basra-Toned Pearls?",
      "Basra-toned pearls offer the timeless elegance associated with historic Basra pearls while being suitable for modern lifestyles. They are loved for their:",
      "- Warm, sophisticated colour",
      "- Classic appeal",
      "- Versatility for everyday and occasion wear",
      "- Elegant pairing with sterling silver and gold",
      "- Timeless style that never goes out of fashion",
      "Whether worn as delicate earrings, graceful necklaces, elegant bracelets, or statement pieces, Basra-toned pearls bring effortless sophistication to every jewellery collection.",
      "### Caring for Your Basra-Toned Pearls",
      "Like all pearls, Basra-toned pearls are organic gemstones and deserve gentle care.",
      "After wearing your jewellery, wipe the pearls with a soft cloth to remove traces of perfume, cosmetics, or natural oils. Store them separately from harder gemstones to avoid scratches, and avoid prolonged exposure to harsh chemicals or excessive heat.",
      "With proper care, your pearls will continue to retain their beautiful lustre for years to come.",
      "### Mahidha's Perspective",
      "At Mahidha, every pearl tells a story.",
      "Our Basra-toned pearls pay tribute to one of the world's most celebrated pearl traditions while embracing the craftsmanship and quality of modern cultured pearls. We carefully select each pearl for its harmonious colour, soft lustre, and natural beauty, creating jewellery that feels timeless, elegant, and effortlessly wearable.",
      "Inspired by history and designed for today, our Basra-toned collections celebrate the enduring charm of pearls while remaining true to our commitment to authenticity and transparency.",
    ],
    facts: [
      ["Pearl Type", "Cultured pearl with a Basra-inspired colour tone"],
      ["Inspiration", "Historic natural Basra pearls of the Arabian Gulf"],
      ["Colour", "Warm ivory, cream, champagne, soft white"],
      ["Lustre", "Soft, satin-like glow"],
      ["Best Known For", "Elegant colour, timeless appeal, everyday sophistication"],
      ["Ideal For", "Necklaces, earrings, bracelets, rings and heirloom-inspired jewellery"],
    ],
    didYouKnow:
      "The legendary Basra pearls that inspired this colour palette were once considered among the most valuable pearls in the world. Today, genuine natural Basra pearls are exceptionally rare, making them prized collector's gems. Basra-toned pearls celebrate the same graceful aesthetic, bringing that timeless elegance into contemporary jewellery through carefully selected cultured pearls.",
  },
];

/* ---------------- Pearl shapes ---------------- */

export interface ShapeCard {
  name: string;
  tagline: string;
  img: GalleryImage;
  paras: string[];
  bestFor: string[];
}

export const SHAPES_INTRO: string[] = [
  "One of the most fascinating things about pearls is that no two are ever exactly alike. While many people imagine pearls as perfectly round, nature creates them in an incredible variety of shapes, each with its own beauty, character, and charm.",
  "The shape of a pearl is influenced by how it grows inside the oyster or mussel. Factors such as the position of the pearl, the movement of the mollusk, and the natural layering of nacre all play a role in determining its final form. Some pearls grow into near-perfect spheres, while others develop graceful drops, soft ovals, or beautifully organic silhouettes.",
  "At Mahidha, we celebrate every shape because each one tells a unique story. Whether perfectly symmetrical or wonderfully freeform, every pearl is a testament to nature's artistry.",
];

export const SHAPES: ShapeCard[] = [
  {
    name: "Round Pearls",
    tagline: "The Timeless Classic",
    img: { src: P + "shape-round.jpg", alt: "A perfectly round pearl" },
    paras: [
      "Round pearls are the most iconic and highly sought-after pearl shape. Their perfect symmetry makes them a timeless choice for necklaces, earrings, bracelets, and rings.",
      "Because perfectly round pearls are rare, they are often considered the most valuable. Their balanced shape reflects light evenly, creating an elegant and refined appearance that never goes out of style.",
    ],
    bestFor: ["Classic pearl necklaces", "Stud earrings", "Tennis bracelets", "Bridal jewellery", "Timeless everyday wear"],
  },
  {
    name: "Near Round Pearls",
    tagline: "Beautifully Balanced",
    img: { src: P + "shape-near-round.jpg", alt: "A near round pearl with subtle natural variation" },
    paras: [
      "Near round pearls appear almost perfectly spherical but may have very slight variations in their shape. These differences are often so subtle that they are difficult to notice without close inspection.",
      "They offer the classic beauty of round pearls while embracing the individuality that naturally occurs during pearl formation. Near round pearls are an excellent choice for those who appreciate elegance with a touch of natural character.",
    ],
    bestFor: ["Everyday necklaces", "Bracelets", "Earrings", "Layering jewellery"],
  },
  {
    name: "Oval Pearls",
    tagline: "Graceful and Elegant",
    img: { src: P + "shape-oval.jpg", alt: "An oval pearl pendant" },
    paras: [
      "Oval pearls have a gently elongated shape that creates an elegant, refined silhouette.",
      "Their graceful proportions make them particularly flattering in pendants and drop earrings, where the elongated form enhances movement and sophistication. Oval pearls are often chosen for jewellery that feels both traditional and contemporary.",
    ],
    bestFor: ["Pendants", "Drop earrings", "Statement necklaces"],
  },
  {
    name: "Button Pearls",
    tagline: "Perfect for Everyday Elegance",
    img: { src: P + "shape-button.jpg", alt: "A button pearl, slightly flattened on one side" },
    paras: [
      "Button pearls are slightly flattened on one side, resembling the shape of a button.",
      "This practical form allows them to sit comfortably against the skin, making them especially popular for earrings, rings, and pendants. Their smooth appearance combines elegance with everyday comfort.",
    ],
    bestFor: ["Stud earrings", "Rings", "Pendants", "Bracelets"],
  },
  {
    name: "Drop Pearls",
    tagline: "Naturally Sophisticated",
    img: { src: P + "shape-drop.jpg", alt: "A teardrop-shaped pearl pendant" },
    paras: [
      "Drop pearls resemble delicate teardrops, making them one of the most elegant pearl shapes.",
      "Their graceful form adds movement and femininity to jewellery, making them particularly popular in pendants and dangling earrings. Drop pearls have long been associated with timeless sophistication and are often chosen for bridal and occasion jewellery.",
    ],
    bestFor: ["Drop earrings", "Pendants", "Bridal jewellery", "Formal occasions"],
  },
  {
    name: "Baroque Pearls",
    tagline: "Beautifully Unique",
    img: { src: P + "shape-baroque.jpg", alt: "Sculptural baroque pearls with organic forms" },
    paras: [
      "Baroque pearls celebrate nature's creativity. Rather than growing into predictable shapes, they develop beautiful curves, ripples, and organic forms that make every pearl completely unique.",
      "Their sculptural appearance has made them a favourite among contemporary jewellery designers, who appreciate their individuality and artistic appeal. At Mahidha, many of our designs embrace the natural beauty of baroque pearls, allowing every piece to feel one of a kind.",
    ],
    bestFor: ["Statement necklaces", "Contemporary earrings", "Designer jewellery", "Artistic collections"],
  },
  {
    name: "Coin Pearls",
    tagline: "Modern and Minimal",
    img: { src: P + "shape-coin.jpg", alt: "Flat, circular coin pearls" },
    paras: [
      "Coin pearls are flat and circular, resembling small coins.",
      "Their smooth surface and contemporary appearance make them a popular choice for modern jewellery designs. They create clean, elegant lines while maintaining the soft beauty that pearls are known for.",
    ],
    bestFor: ["Layered necklaces", "Bracelets", "Modern earrings", "Minimalist jewellery"],
  },
  {
    name: "Rice Pearls",
    tagline: "Delicate and Versatile",
    img: { src: P + "shape-rice.jpg", alt: "Delicate strands of rice pearls" },
    paras: [
      "Rice pearls are small, elongated pearls that resemble grains of rice.",
      "They are lightweight, delicate, and incredibly versatile, making them ideal for layered necklaces, bracelets, and intricate handcrafted designs. Their elegant proportions add texture and movement to jewellery without overwhelming the design.",
    ],
    bestFor: ["Layered necklaces", "Pearl strands", "Bracelets", "Handcrafted jewellery"],
  },
];

export const SHAPES_OUTRO: string[] = [
  "### Why Pearl Shape Matters",
  "Every pearl shape brings its own personality to a piece of jewellery.",
  "Round pearls offer timeless elegance, while baroque pearls celebrate individuality. Drop pearls create graceful movement, button pearls provide everyday comfort, and coin or rice pearls introduce a contemporary touch.",
  "There is no “best” shape. The perfect pearl is the one that reflects your personal style and the story you want your jewellery to tell.",
  "At Mahidha, we thoughtfully select each pearl not only for its lustre and quality but also for how its natural shape complements the design.",
  "### Mahidha's Perspective",
  "We believe the beauty of pearls lies in their individuality.",
  "Rather than trying to make every pearl look the same, we embrace the subtle differences that nature creates. Whether it's a perfectly round pearl or a beautifully sculpted baroque pearl, every shape has its own character and charm.",
  "Our collections are designed to celebrate this diversity, creating jewellery that feels elegant, authentic, and timeless.",
];

export const SHAPES_TABLE: { head: string[]; rows: string[][] } = {
  head: ["Shape", "Appearance", "Best For"],
  rows: [
    ["Round", "Perfectly spherical", "Necklaces, stud earrings, classic jewellery"],
    ["Near Round", "Almost round", "Everyday jewellery, layering"],
    ["Oval", "Softly elongated", "Pendants, earrings"],
    ["Button", "Slightly flattened", "Stud earrings, rings"],
    ["Drop", "Teardrop shape", "Pendants, drop earrings"],
    ["Baroque", "Irregular, organic", "Statement jewellery, contemporary designs"],
    ["Coin", "Flat and circular", "Modern necklaces, bracelets"],
    ["Rice", "Small and elongated", "Layered jewellery, handcrafted designs"],
  ],
};

/* ---------------- Pearl colours ---------------- */

export interface ColourCard {
  name: string;
  tagline: string;
  img: GalleryImage;
  body: string[];
}

export const COLOURS_INTRO: string[] = [
  "One of the greatest misconceptions about pearls is that they are only white. In reality, pearls are found in a remarkable spectrum of natural colours, each created by the type of mollusk, the waters in which it grows, and the unique conditions of its environment.",
  "From the timeless beauty of classic white pearls to the warm glow of golden South Sea pearls and the dramatic hues of Tahitian pearls, every colour tells a different story. Some shades are soft and understated, while others are bold and captivating, offering endless possibilities for personal style.",
  "At Mahidha, we celebrate this natural diversity. Every pearl is carefully selected for its colour, lustre, and harmony, ensuring each piece reflects the quiet elegance that makes pearls so enduring.",
  "### What Determines a Pearl's Colour?",
  "A pearl's colour is entirely natural and influenced by several factors, including:",
  "- The species of oyster or mussel",
  "- The colour of the mollusk's shell",
  "- The waters in which the pearl grows",
  "- The thickness of the nacre",
  "- Natural pigments produced during formation",
  "Together, these elements create the pearl's unique appearance. This is why no two pearls are ever exactly the same, even when they come from the same farm.",
  "Gemologists often describe a pearl's appearance using three characteristics:",
  "- Body Colour — the pearl's main colour.",
  "- Overtone — a subtle secondary colour that appears over the body colour.",
  "- Orient — a rare iridescent effect where multiple colours shimmer across the surface.",
  "These natural characteristics give pearls their remarkable depth and individuality.",
];

export const COLOURS: ColourCard[] = [
  {
    name: "White Pearls",
    tagline: "The Timeless Classic",
    img: { src: P + "colour-white.jpg", alt: "Classic white pearl strands" },
    body: [
      "White pearls are the most recognisable and enduring choice in pearl jewellery. Their fresh, luminous appearance symbolises purity, elegance, and sophistication. Whether worn every day or reserved for life's special moments, white pearls remain effortlessly versatile.",
      "Commonly found in freshwater, Akoya, and South Sea pearls, they pair beautifully with sterling silver, white gold, and platinum, making them a timeless addition to any jewellery collection.",
    ],
  },
  {
    name: "Ivory & Cream Pearls",
    tagline: "Warm and Refined",
    img: { src: P + "colour-ivory.jpg", alt: "Warm ivory and cream pearl strand" },
    body: [
      "Ivory and cream pearls offer a softer, warmer alternative to bright white pearls. Their subtle warmth creates a graceful, vintage-inspired elegance that flatters every skin tone. These colours are especially popular in heirloom-style jewellery and contemporary minimalist designs.",
      "They are often found in freshwater, South Sea, and Basra-toned pearls. Their understated beauty makes them one of the most versatile pearl colours.",
    ],
  },
  {
    name: "Pink & Peach Pearls",
    tagline: "Softly Romantic",
    img: { src: P + "colour-pink.jpg", alt: "Naturally pink and peach pearls" },
    body: [
      "Pink and peach pearls are admired for their delicate, feminine charm. These naturally warm shades bring freshness and softness to jewellery, making them a popular choice for gifts, bridal jewellery, and everyday elegance.",
      "They are most commonly found in freshwater pearls, and their gentle glow pairs beautifully with both sterling silver and rose gold.",
    ],
  },
  {
    name: "Lavender Pearls",
    tagline: "A Contemporary Favourite",
    img: { src: P + "colour-lavender.jpg", alt: "Soft lavender freshwater pearls" },
    body: [
      "Lavender pearls offer a subtle touch of colour while maintaining the timeless elegance of traditional pearls. Their soft pastel tones make them an ideal choice for those seeking something unique yet understated.",
      "Lavender pearls are primarily found in freshwater pearl cultivation and have become increasingly popular in modern jewellery designs.",
    ],
  },
  {
    name: "Golden Pearls",
    tagline: "Luxury in Its Purest Form",
    img: { src: P + "colour-golden.jpg", alt: "Rich golden South Sea pearl strand" },
    body: [
      "Golden pearls are among the rarest and most valuable pearls in the world. Produced naturally by the Gold-Lipped South Sea Oyster, their rich golden tones develop entirely through nature rather than artificial colouring.",
      "Their shades range from champagne to light gold and deep gold. Golden pearls are admired for their warmth, rarity, and luxurious appearance, making them highly sought after by collectors and jewellery enthusiasts.",
    ],
  },
  {
    name: "Silver Pearls",
    tagline: "Modern and Sophisticated",
    img: { src: P + "colour-silver.jpg", alt: "A cool-toned silver pearl" },
    body: [
      "Silver pearls have a cool, elegant tone that feels effortlessly contemporary. Their refined appearance pairs beautifully with platinum, sterling silver, and white gold, making them a favourite for minimalist jewellery.",
      "Silver tones are commonly found in South Sea and Tahitian pearls.",
    ],
  },
  {
    name: "Grey & Peacock Pearls",
    tagline: "Bold and Distinctive",
    img: { src: P + "colour-peacock.jpg", alt: "Tahitian pearls with peacock overtones" },
    body: [
      "Grey and peacock pearls are the signature colours of Tahitian pearls. Peacock pearls display a fascinating blend of green, blue, and purple overtones that shift as they catch the light. This complex colouring gives every pearl remarkable depth and individuality.",
      "These colours are entirely natural and are among the most prized in the world of pearls.",
    ],
  },
];

export const COLOURS_OUTRO: string[] = [
  "### Choosing the Right Pearl Colour",
  "There is no single “best” pearl colour. The perfect choice depends on your personal style, wardrobe, and the occasions for which you plan to wear your jewellery.",
  "- White offers timeless elegance.",
  "- Cream and Ivory create a warm, classic look.",
  "- Pink and Peach feel soft and romantic.",
  "- Lavender adds a contemporary touch.",
  "- Golden embodies luxury and rarity.",
  "- Silver delivers modern sophistication.",
  "- Grey and Peacock make a bold, elegant statement.",
  "The beauty of pearls lies in their diversity, allowing every wearer to find a colour that feels uniquely their own.",
  "### Mahidha's Perspective",
  "At Mahidha, colour is never chosen by trend alone. We carefully select pearls for their natural beauty, ensuring every shade complements the design while allowing the pearl's individuality to shine.",
  "Whether it's the classic elegance of white freshwater pearls, the warm sophistication of Basra-toned pearls, the luxurious glow of South Sea pearls, or the dramatic beauty of Tahitian pearls, each colour is chosen to celebrate nature's artistry.",
  "To us, every pearl tells its own story, and colour is one of the most beautiful chapters.",
];

export const COLOURS_TABLE: { head: string[]; rows: string[][] } = {
  head: ["Colour", "Common Pearl Type", "Character"],
  rows: [
    ["White", "Freshwater, Akoya, South Sea", "Classic, timeless, elegant"],
    ["Cream", "Freshwater, South Sea, Basra-toned", "Warm, refined, versatile"],
    ["Ivory", "Freshwater, South Sea, Basra-toned", "Soft, sophisticated"],
    ["Pink", "Freshwater", "Romantic and feminine"],
    ["Peach", "Freshwater", "Warm and contemporary"],
    ["Lavender", "Freshwater", "Modern and distinctive"],
    ["Golden", "South Sea", "Luxurious and rare"],
    ["Silver", "South Sea, Tahitian", "Cool and elegant"],
    ["Grey", "Tahitian", "Bold and modern"],
    ["Peacock", "Tahitian", "Rich, iridescent, highly prized"],
  ],
};

export const COLOURS_DYK =
  "Unlike many gemstones, pearls are born with their colour. While some pearls in the market may be enhanced after harvesting, many of the world's most beautiful pearls, including South Sea golden pearls and Tahitian pearls, develop their remarkable colours naturally inside the oyster. That is one of the reasons every pearl is truly one of a kind.";

/* ---------------- Pearl lustre ---------------- */

export const LUSTRE_IMAGES: GalleryImage[] = [
  { src: P + "lustre-1.jpg", alt: "A pearl with excellent lustre and a deep inner glow" },
  { src: P + "lustre-2.jpg", alt: "A lustrous pearl resting on satin" },
  { src: P + "lustre-3.jpg", alt: "A silvery pearl with sharp, clear reflections" },
];

export const LUSTRE_BODY: string[] = [
  "When choosing a pearl, many people focus on its size or colour. While these characteristics are certainly important, experts agree that lustre is the single most important factor in determining a pearl's beauty and value.",
  "Lustre is what gives a pearl its life. It is the soft glow that seems to come from within, the way light dances across its surface, and the depth that makes a pearl appear almost luminous. A pearl with exceptional lustre instantly captures attention, while a pearl with poor lustre can appear dull, even if it is perfectly round or large.",
  "At Mahidha, lustre is one of the first qualities we look for when selecting pearls. It is the feature that transforms a beautiful pearl into an extraordinary one.",
  "### What Is Pearl Lustre?",
  "Lustre refers to the way light interacts with the surface and inner layers of a pearl.",
  "As light reaches the pearl, some of it reflects from the surface while some passes through the translucent layers of nacre before reflecting back. This combination creates the soft, radiant glow that pearls are famous for. The finer and more uniform the layers of nacre, the richer and more vibrant the lustre becomes.",
  "Unlike diamonds, which sparkle through facets, pearls glow through their nacre. This unique quality gives pearls a gentle elegance that no other gemstone can replicate.",
  "### Why Is Lustre So Important?",
  "Lustre is often described as the “soul” of a pearl.",
  "A pearl with excellent lustre appears bright, crisp, and full of life. You can often see sharp reflections of nearby objects on its surface. A pearl with poor lustre, on the other hand, looks flat, chalky, or cloudy because it reflects very little light.",
  "This is why two pearls of the same size and colour can have completely different values. The one with better lustre is almost always considered more desirable.",
  "### What Creates Beautiful Lustre?",
  "Several natural factors influence a pearl's lustre.",
  "#### Thick Nacre",
  "Nacre is the smooth substance that forms the pearl. The thicker and more even the nacre, the more beautifully light travels through the pearl, creating depth and radiance. This is one reason why South Sea pearls are admired for their luxurious glow.",
  "#### Healthy Oysters and Mussels",
  "Only healthy mollusks growing in clean, nutrient-rich waters can produce pearls with exceptional lustre. Water quality, temperature, and natural conditions all play an important role.",
  "#### Time",
  "Pearls cannot be rushed. The longer a pearl remains inside the oyster or mussel, the more layers of nacre develop, resulting in richer lustre and greater durability. Nature rewards patience.",
  "### Different Types of Lustre",
  "Every pearl variety has its own distinctive style of lustre.",
  "#### Freshwater Pearls",
  "Freshwater pearls are known for their soft, silky glow. Their lustre feels gentle and elegant, making them perfect for everyday jewellery.",
  "#### South Sea Pearls",
  "South Sea pearls display a rich, satin-like lustre with remarkable depth. Their glow appears luxurious and velvety rather than sharply reflective.",
  "#### Tahitian Pearls",
  "Tahitian pearls are admired for their reflective lustre combined with dramatic natural overtones. Their colours seem to change as they catch the light, creating exceptional depth.",
  "#### Basra-Toned Pearls",
  "Basra-toned pearls are appreciated for their warm, understated glow. Their soft lustre reflects the quiet elegance that inspired their name.",
  "### Understanding Lustre Quality",
  "Pearl experts generally describe lustre using four levels.",
  "#### Excellent Lustre",
  "Bright reflections, sharp and clear images, a strong inner glow, and exceptional depth. These pearls are considered the finest quality.",
  "#### Very Good Lustre",
  "A bright surface, good reflections, and a beautiful glow with minor softness in reflection. These pearls are ideal for fine jewellery.",
  "#### Good Lustre",
  "A pleasant shine, softer reflections, and a gentle glow. These pearls remain attractive while offering excellent everyday wearability.",
  "#### Fair to Low Lustre",
  "A dull appearance, blurred reflections, little depth, and a chalky surface. These pearls are generally considered lower in quality.",
  "### How to Check Pearl Lustre",
  "Even without professional equipment, you can evaluate a pearl's lustre by observing it in natural light. Ask yourself:",
  "- Does the pearl reflect light clearly?",
  "- Can you see a crisp reflection?",
  "- Does it appear bright or dull?",
  "- Does the glow seem to come from within?",
  "- Does the surface look smooth and alive?",
  "High-quality pearls almost appear illuminated from the inside.",
  "### Lustre vs Shine",
  "Although the words are often used interchangeably, they are not the same.",
  "Shine refers to simple surface reflection. Lustre refers to the depth, glow, and interaction of light within the pearl's nacre.",
  "A polished bead may shine, but only a genuine pearl possesses true lustre. This is one of the qualities that makes pearls unlike any other gemstone.",
  "### Can Pearls Lose Their Lustre?",
  "Yes, but only if they are not cared for properly.",
  "Exposure to harsh chemicals, perfumes, cosmetics, excessive heat, or improper storage can gradually affect the surface of a pearl. Fortunately, caring for pearls is simple.",
  "- Put your pearls on after applying perfume and makeup.",
  "- Wipe them gently with a soft cloth after wearing.",
  "- Store them separately from harder jewellery.",
  "- Avoid prolonged exposure to chlorinated water or household cleaners.",
  "With proper care, pearls can maintain their beautiful lustre for generations.",
  "### Mahidha's Perspective",
  "At Mahidha, we believe lustre is what gives a pearl its soul.",
  "When selecting pearls for our collections, we look beyond size and shape. We search for pearls with exceptional radiance, beautiful depth, and the quiet glow that only nature can create.",
  "Whether it is the silky elegance of a freshwater pearl, the luxurious satin finish of a South Sea pearl, the dramatic reflections of a Tahitian pearl, or the warm glow of our Basra-toned pearls, lustre remains at the heart of every piece we create.",
  "Because the true beauty of a pearl is not measured by how brightly it shines, but by how beautifully it glows.",
];

export const LUSTRE_TABLE: { head: string[]; rows: string[][] } = {
  head: ["Lustre Level", "Appearance", "Quality"],
  rows: [
    ["Excellent", "Bright, sharp reflections with deep inner glow", "Exceptional"],
    ["Very Good", "Strong shine with clear reflections", "Premium"],
    ["Good", "Soft glow with moderate reflections", "Fine"],
    ["Fair", "Dull appearance with blurred reflections", "Commercial"],
  ],
};

/* ---------------- Pearl care ---------------- */

export const CARE_IMAGES: GalleryImage[] = [
  { src: P + "care-1.jpg", alt: "Wiping a pearl necklace gently with a soft cloth" },
  { src: P + "care-2.jpg", alt: "Storing pearls in a soft pouch inside a jewellery box" },
  { src: P + "care-3.jpg", alt: "A pearl necklace resting in a soft fabric pouch" },
];

export const CARE_BODY: string[] = [
  "Pearls are unlike any other gemstone. Created by living oysters and mussels, they are organic gems with a natural beauty that has captivated people for centuries. Their soft glow and delicate surface deserve thoughtful care, but maintaining their beauty is simpler than many people think.",
  "With just a few mindful habits, your pearl jewellery can retain its lustre for generations, becoming a cherished heirloom passed down through the family.",
  "At Mahidha, every pearl is selected for its beauty and craftsmanship. We believe that caring for your jewellery is just as important as choosing it.",
  "### Pearls Are Meant to Be Worn",
  "One of the most common myths is that pearls should be locked away for special occasions. In reality, pearls are happiest when they are worn regularly.",
  "The natural oils from your skin help maintain their lustre and prevent them from becoming excessively dry over time. Rather than saving your pearls for rare occasions, enjoy them as part of your everyday style. Like all treasured possessions, they simply deserve a little care.",
  "### Last On, First Off",
  "One simple rule will help protect your pearls: your pearls should be the last thing you put on and the first thing you take off.",
  "Perfumes, hairsprays, makeup, sunscreen, and lotions often contain chemicals that can gradually affect the pearl's surface. Complete your skincare and beauty routine first, then wear your pearl jewellery. At the end of the day, remove your pearls before taking off your makeup or applying skincare products.",
  "### Wipe Them After Every Wear",
  "Pearls naturally absorb traces of cosmetics, perfume, perspiration, and environmental dust.",
  "After wearing your jewellery, gently wipe each pearl with a clean, soft, lint-free cloth. This simple habit removes residue before it has a chance to build up and helps preserve the pearl's natural lustre. Avoid using rough fabrics or abrasive materials.",
  "### Store Pearls Separately",
  "Although pearls look delicate, they can easily be scratched by harder gemstones and metals. Store your pearl jewellery separately in:",
  "- A soft fabric pouch",
  "- A lined jewellery box",
  "- A silk or velvet compartment",
  "Avoid allowing pearls to rub against diamonds, sapphires, or metal chains during storage. A little separation goes a long way in preserving their smooth surface.",
  "### Avoid Harsh Chemicals",
  "Pearls are sensitive to many household and cosmetic products. Try to avoid direct contact with:",
  "- Perfume",
  "- Hair spray",
  "- Lotions",
  "- Sunscreen",
  "- Household cleaning products",
  "- Bleach",
  "- Vinegar",
  "- Strong detergents",
  "These substances may gradually dull the pearl's surface and reduce its natural lustre.",
  "### Keep Pearls Away from Water",
  "While pearls naturally grow in water, finished pearl jewellery should not be exposed to prolonged moisture. It is best to remove your pearls before:",
  "- Swimming",
  "- Showering",
  "- Bathing",
  "- Visiting a sauna",
  "- Entering a hot tub",
  "Chlorine, saltwater, soaps, and excessive moisture can weaken silk threads and affect the pearl's surface over time.",
  "### Protect Them from Heat",
  "Extreme heat and prolonged direct sunlight may gradually dry out organic gemstones.",
  "Store your pearls in a cool, dry place away from direct sunlight, radiators, and excessive humidity. Stable conditions help preserve both the pearls and the thread used in pearl necklaces.",
  "### Travelling with Pearl Jewellery",
  "When travelling, keep your pearls in a soft travel pouch or a dedicated jewellery case.",
  "Avoid tossing them loosely into handbags or luggage where they may rub against other jewellery or hard objects. A little protection ensures they arrive looking just as beautiful as when you packed them.",
  "### Should Pearl Necklaces Be Restrung?",
  "If you wear your pearl necklace regularly, it is a good idea to have it professionally inspected every few years.",
  "Over time, the silk thread may naturally stretch through daily wear. Professional restringing helps maintain both the beauty and security of your jewellery.",
  "Many luxury jewellers recommend restringing well-loved pearl necklaces approximately every one to three years, depending on how frequently they are worn.",
  "### Cleaning Your Pearls",
  "Pearls require very little cleaning. Simply use:",
  "- A soft, damp cloth if necessary",
  "- Clean water only",
  "- A dry lint-free cloth for polishing afterwards",
  "Avoid ultrasonic cleaners, steam cleaners, jewellery cleaning chemicals, abrasive brushes, and toothpaste or baking soda. These methods are suitable for diamonds and metals but not for pearls.",
  "### Everyday Care Tips",
  "A few simple habits will keep your pearls looking beautiful for years.",
  "- Wear them often.",
  "- Apply perfume and makeup before putting them on.",
  "- Wipe them clean after every wear.",
  "- Store them separately.",
  "- Remove them before swimming or showering.",
  "- Handle them gently.",
  "These small steps make a lasting difference.",
  "### Mahidha's Perspective",
  "At Mahidha, we believe pearls are made to become part of your life's journey, not hidden away in a jewellery box.",
  "Every pearl carries the quiet beauty of nature and the skill of the artisans who transform it into jewellery. With thoughtful care, your pearl jewellery will continue to shine through everyday moments, family celebrations, and memories yet to be made.",
  "We hope every Mahidha piece becomes more than an accessory. We hope it becomes part of your story.",
];

export const CARE_TABLE: { head: string[]; rows: string[][] } = {
  head: ["Do", "Don't"],
  rows: [
    ["Wear your pearls regularly", "Spray perfume directly on pearls"],
    ["Wipe them with a soft cloth after wearing", "Use harsh jewellery cleaners"],
    ["Store them in a soft pouch or lined jewellery box", "Store them with diamonds or other hard gemstones"],
    ["Remove them before swimming or showering", "Wear them in chlorinated pools or hot tubs"],
    ["Keep them away from excessive heat and chemicals", "Leave them in direct sunlight for long periods"],
    ["Have pearl strands checked and restrung when needed", "Pull or stretch pearl strands"],
  ],
};
